### ISSUE TITLE
Some enhancements for your project

### ISSUE THREAD

**Issue by icecodder** [Mw3y/Suivix#10]
Hey, I saw your project on news, its a good idea!
I would like to suggest some enhancements for your project.

- [ ] Use something better than express for your web server like koa or fastify, express is a good web server but its very old and it can create a lot of errors
- [ ] Use TypeScript instead of JavaScript, TypeScript is a superset of JavaScript so syntax is almost the same but the support ES6 spec, it has a real OOP not like JS, you can type (as its name) your variable so you will have much less error. For more information [the TypeScript website](https://www.typescriptlang.org/) is a good place!
- [ ] Create a doc for your projects, when I saw the site I feel lost there is no documentation on how to use it
- [ ] Use CI for automation, like autodeployement, check test, see code quality, etc
- [ ] Implement sharding and/or clustering with discord shard and kubernetes
- [ ] Add code of conduct, contributing guide, template for issue and pr, etc

So, I think I've already given a lot of ideas.
Also, **I'm french** and use Discord all the time, so if you want to contact me more easily use Discord `icecodder#0069`
And why not join you dev team!

**Comment by Mw3y** [comment]
I am currently rewriting Suivix. Most of these suggestions will be implemented.
